version: 2
updates:
- package-ecosystem: docker
  directory: "/docker"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
    - "docker"
    - "dependencies"
- package-ecosystem: cargo
  directory: "/sidre"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "cargo"
    - "dependencies"
- package-ecosystem: cargo
  directory: "/prost-sled"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "cargo"
    - "dependencies"
- package-ecosystem: cargo
  directory: "/xtask"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "cargo"
    - "dependencies"
- package-ecosystem: python
  directory: "/test-service-provider"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "python"
    - "dependencies"