version: "3.7"

services:
    pg:
        image: postgres
        environment:
            POSTGRES_DB: "sidre"
            POSTGRES_USER: "sidre"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"

    sidre-test:
        build:
            dockerfile: ./docker/Dockerfile.test
            context: .
        volumes:
            - .:/workspace
        command: cargo test --verbose
        environment:
            DATABASE_URL: "postgres://sidre:password@pg/sidre"
            RUST_LOG: "info"
            SQLX_OFFLINE: "true"

    sidre-dev:
        build:
            dockerfile: ./docker/Dockerfile.dev
            context: .
        volumes:
            - .:/workspace
        ports:
            - "8080:8080"
        environment:
            DATABASE_URL: "postgres://sidre:password@pg/sidre"
            RUST_LOG: "info"

    test-service-provider:
        image: nick96/test-service-provider
        ports:
            - "5000:5000"

