version: "3.7"

services:
    pg:
        image: postgres
        environment:
            POSTGRES_DB: "sidre"
            POSTGRES_USER: "sidre"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"

    sidre-vscode:
        build:
            dockerfile: ../docker/Dockerfile.vscode
            context: ./sidre
        volumes:
            - .:/workspace:cached
        command: '/bin/sh -c "while sleep 1000; do :; done"'
        environment:
            DATABASE_URL: "postgres://sidre:password@pg/sidre"
