unstable_features = true
max_width = 80
format_strings = false
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
format_code_in_doc_comments = true
wrap_comments = true
