FROM rustlang/rust:nightly-slim

WORKDIR /workspace

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
        pkg-config libssl-dev build-essential xml-security-c-utils libxmlsec1-dev libclang-dev clang llvm libxml2-dev

RUN rustup install stable-x86_64-unknown-linux-gnu

RUN rustup component add clippy
RUN rustup component add --toolchain stable rustfmt
RUN cargo install --version=0.1.0-beta.1 sqlx-cli --no-default-features --features postgres