version: "3.7"

services:
    pg:
        image: postgres
        environment:
            POSTGRES_DB: "sidre"
            POSTGRES_USER: "sidre"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
    
    sidre-vscode:
        build:
            dockerfile: .devcontainer/Dockerfile
            context: .
        environment:
            DATABASE_URL: "postgres://sidre:password@pg/sidre"
