name: Dependabot
on:
  pull_request:
    types: [ labeled ]

jobs:
  approve:
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install gh
        run: |
          curl -L https://github.com/cli/cli/releases/download/v1.4.0/gh_1.4.0_linux_amd64.deb >gh.deb &&
            sudo apt-get install -y ./gh.deb
      - name: Configure gh
        run: |
          gh config set prompt disabled
      - name: Approve for bors
        run: |
          gh pr review ${{github.event.number}} -c -b "bors r+"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
