name: Release

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ghcr.io/nick96/sidre

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 1
        - name: Build image (release)
          run: docker build -t ${IMAGE_NAME} -f docker/Dockerfile.release .
        - name: Tag with commit SHA
          run: docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${GITHUB_SHA::7}
        - name: Log in to registry
          run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        - name: Push images to registry
          run: |
            docker push ${IMAGE_NAME}:${GITHUB_SHA::7}
            docker push ${IMAGE_NAME}:latest
        
