name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  SIDRE_TEST_IMAGE_NAME: build-cache-sidre-test

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - name: Pull the image (cache)
      run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/$SIDRE_TEST_IMAGE_NAME || true
    - name: Build the image
      run: docker build --file ./docker/Dockerfile.dev . -t thing --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/$SIDRE_TEST_IMAGE_NAME
    - name: Tag the new docker image
      run: |
        docker tag thing docker.pkg.github.com/$GITHUB_REPOSITORY/$SIDRE_TEST_IMAGE_NAME && \
         docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$SIDRE_TEST_IMAGE_NAME || true
    - name: Run Test
      run: docker-compose run sidre-test cargo test --verbose

  formatting:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: docker-compose run sidre-test cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: docker-compose run sidre-test cargo clippy -- -D warnings

  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build release docker image
      run: docker build -t nick96/sidre -f docker/Dockerfile.release .
