name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx
    - uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/Dockerfile.test
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: docker.pkg.github.com/${{ github.repository }}/build-cache-sidre-test
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    - name: Run test
      run: docker run docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-sidre-test cargo test --verbose

  formatting:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: docker-compose run sidre-test cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: docker-compose run sidre-test cargo clippy -- -D warnings

  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build release docker image
      run: docker build -t nick96/sidre -f docker/Dockerfile.release .
