name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run Test
      run: cargo xtask dc test

  formatting:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo xtask dc check-fmt

  clippy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo xtask dc lint

  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build release docker image
      run: docker build -t nick96/sidre -f docker/Dockerfile.release .
