name: Test service provider

on:
  push:
    branches:
      - main
    paths:
      - "test-service-provider/**"
      - ".github/workflows/test-service-provider.yml"
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and publish
        run: make publish GIT_SHA=${GITHUB_SHA:0:7}